version: '3.8'

services:
  nuka_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: nuka_service
    container_name: nuka_service
    restart: unless-stopped
    ports:
      - "1080:1080"
